<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.6" />
    <PackageReference Include="MudBlazor" Version="8.9.0" />
  </ItemGroup>

   <Target Name="NSwag">
      <Exec WorkingDirectory="$(ProjectDir)\api" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development" Command="nswag run ./nswag.json /variables:Configuration=$(Configuration)" />
   </Target>

</Project>
