<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Notes\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Notes.Infrastructure\Notes.Infrastructure.csproj" />
  </ItemGroup>

</Project>
